[package]
name = "typevec"
version = "0.1.0"
authors = ["sinhrks <sinhrks@gmail.com>"]
repository = "https://github.com/sinhrks/rust-typevec"
license-file = "LICENSE"
readme = "README.md"
description = "Rust Vec which can contain arbitrary types"

[dependencies]
unsafe-any = "0.4.1"
